food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    #/food/
    path('',views.IndexClassView.as_view(),name= "index" ),
    #/food/1
    path('<int:pk>/',views.FoodDetail.as_view(),name='details'),
    path('item',views.item,name='item'),
    # add item 
    path('add',views.CreateItem.as_view(),name="create_item" ),
    #edit item
    path('update/<int:id>/',views.update_item,name="update_item"),
    # delete item
    path('delete/<int:id>/',views.delete_item,name='delete_item'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include ('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profle_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class Itemform(forms.ModelForm):
    class Meta:
        model = Item
        fields =['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User  
        fields = ['username','email','password1','password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import Itemform
from .models import Item 
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.
def index (request):
    item_list = Item.objects.all()
    template= loader.get_template ('food/index.html')
    context = {
        'item_list':item_list,
    }

    return render(request,'food/index.html',context)

class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'

def details(request,item_id):
    item = Item.objects.get(pk=item_id)
    context ={
        'item' :item,
    }
    return render(request,'food/details.html',context)

class FoodDetail(DetailView):
    model = Item;
    template_name = 'food/details.html'
    

def item (request):
    return HttpResponse('This is a item view')

def create_item(request):
    form  = Itemform(request.POST or None)

    if form.is_valid():
        form.save()
        return  redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = Itemform(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render (request,'food/item-form.html',{'form':form , 'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)
    
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created.')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        <title>Document</title>
        <link rel ="stylesheet" href="{% static 'food/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>

        <div class="navbar nav">
            <a href="{% url 'food:create_item' %}" class="nav-item nav-link" >Add Item</a>
            <a class="nav-item nav-link" href="#">Delete Item</a>
            <a class="nav-item nav-link " href="#">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    
    {% block body %}
    {% endblock%}
</body>
</html>

food/templates/food/details.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img class="cards" height="300px" src="{{ item.item_image }}"/>
            </div>
            <div class="col-md-6">
                <h1>{{ object.item_name }}</h1>
                <h2>{{ object.item_desc }}</h2>
                <h3>₹{{ object.item_price }}</h3>
                <a href="{% url 'food:delete_item' item.id %}">Delete</a>
            </div>
        </div>
    </div>

{% endblock%}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    </head>
<body>

    {% block body %}

        {% for item in item_list %}  
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="cards" height="150px" src="{{ item.item_image }}"/>
            </div>
            <div class="col-md-4 ">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>₹{{ item.item_price }}</h6>
                <h6>{{ item.user_name }}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:details' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
        
    {% endfor %}

    {% endblock%}

    <ul>
        <li>
            <a href = ""> {{item.id}} -- {{ item.item_name}}</a>
        </li>
    </ul>
    
</body>
</html>

food/templates/food/item-delete.html
<form method="post">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm </button>
</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="class-header text-white bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{form}}
                        <button  class="btn-info" type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="class-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}


<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form>

users/templates/users/logout.html
<h1>You have been logged out</h1>

users/templates/users/profile.html
<h1>{{ user.username}}</h1>
<img width="100px" height="100px" src="{{ user.profile.image.url }}">

users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="class-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.name }}
                            <br>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button class="btn-info" type="submit">Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}